### ISSUE TITLE
[Flash] Allow people to submit a Flash game/animation even if they do not have the SWF

### ISSUE THREAD

**Issue by cst-master** [BeatableMeat/beatablemeat.github.io#16]
You could add a button on the website that goes here, possibly.

**Comment by sabianroberts** [comment]
# Hi, @classictourneys, thank you for submitting to our forums.
Though the Flash Repo is part of the Beatable Meat project, I do not have edit permissions for the repository or the website hosting it. I will contact the developer (they will have a GitHub account as @harry-phoenix soon) of the website and notify them about this issue request.

About requesting a game without the SWF file, when the developer of the site is notified, I will add labels here and you will be allowed to put the requests on here.

**Comment by sabianroberts** [comment]
# Hi @classictourneys, the developer of the Flash Repo gave me access and I have added the option to the site. [Take a look.](https://sites.google.com/view/flashrepo/home#h.p_ZM8BgKQ3Dtr6)
