### ISSUE TITLE
[GitHub] Create a branch / new repo for the SDK Base

### ISSUE THREAD

**Issue by sabianroberts** [BeatableMeat/beatablemeat.github.io#18]
Since we’re allowing people to clone this and edit it for their own Portal type of website, I’m pretty sure they won’t want to get rid of the Beatable Meat stuff on there. There should be a branch where the needed pages are blank (not BLANK blank, but you know what I mean) for people to easily edit the site.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sabianroberts** [comment]
I think @HeatwaveStudios is about to do this

**Comment by chinshark-heatwave** [comment]
# @sabian-heatwave Repo created!!! https://github.com/heatwavestudios/portal

**Comment by sabianroberts** [comment]
Nice @chinshark-heatwave
