### ISSUE TITLE
[BG] [BGHTM] All Games Missing (error 404)

### ISSUE THREAD

**Issue by sabianroberts** [BeatableMeat/beatablemeat.github.io#20]
Because of the code overhaul

**Comment by sabian-heatwave** [comment]
# Turns out it happens with all games due to the big overhaul. I’ll update this issue tomorrow. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sabianroberts** [comment]
See commit [ae75dd7](https://github.com/BeatableMeat/beatablemeat.github.io/commit/ae75dd70504d8366ede400b6868e6ed96d651080)
