### ISSUE TITLE
A NOTICE FROM HEATWAVE STUDIOS

### ISSUE THREAD

**Issue by chinshark-heatwave** [BeatableMeat/beatablemeat.github.io#26]
Please add the NEW license of HeatwaveStudios/portal to this.

**Comment by sabianroberts** [comment]
I will get to work on it right away.

**Comment by sabianroberts** [comment]
See commit [f8ad689](https://github.com/BeatableMeat/beatablemeat.github.io/commit/f8ad689b9b2bb2c3805c1ff5871fad45086f7f81)
