### ISSUE TITLE
[Portal] Add a style CSS file

### ISSUE THREAD

**Issue by BeatableMeat** [BeatableMeat/beatablemeat.github.io#7]
The code in the HTML files created by @sabian-heatwave and @daniel-heatwave are unnecessarily big and this is partly due to styles such as fonts. It would be easier to create a `styles.css` file and define the styles for links, headers and paragraph text there. It will make less hassle when editing and creating new pages.

**Comment by sabianroberts** [comment]
Thank you, whoever posted this on the main @BeatableMeat account.
I will begin working on a styles.css and notify @daniel-heatwave of the change.

**Comment by sabianroberts** [comment]
I have added the [styles.css](https://github.com/BeatableMeat/beatablemeat.github.io/blob/master/styles.css) file and now there is less time-wasting code.
