### ISSUE TITLE
[Portal] Add a button on the portal that links to this repository

### ISSUE THREAD

**Issue by cst-master** [BeatableMeat/beatablemeat.github.io#8]
Hi,
I think that it would be handy if people will be redirected to here with the handy click of a button on the actual website, it could say "Source code of Beatable Meat Portal" or something like that
Also include separate buttons to go to the issues page as most people will want to go there most probably

Thank you for considering my idea

### Note from the moderator
I have fixed the incorrect spelling of "separate" in this post.

**Comment by sabianroberts** [comment]
Hi @classictourneys, your suggestion to improve the Beatable Meat Portal has been considered and I have put it on the to-do list. The change should come within the next two or three commits.
